//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class CareerPlan : Observable, Observer
{
	private string planId
	{
		get;
		set;
	}

	private DocumentContext CareerTemplate
	{
		get;
		set;
	}

	private string faculty
	{
		get;
		set;
	}

	public virtual TEC_CEDA TEC_CEDA
	{
		get;
		set;
	}

	public virtual DocumentContext getDocument()
	{
		throw new System.NotImplementedException();
	}

	public virtual void setDocument(DocumentContext pDocument)
	{
		throw new System.NotImplementedException();
	}

}

