//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class CEDAManager : User
{
    public TEC_CEDA TEC_CEDA;

    public CEDAManager(string pName, string pEmail, TEC_CEDA plantilla) : base(pName, pEmail)
    {
        this.TEC_CEDA = plantilla;
    }

    public override void addComponent(string pParentID, Component pComponent)
    {
        this.TEC_CEDA.addComponent(pParentID, pComponent, UserType.CEDAManager);
    }

    public override void editComponent(string pID, Component pComponentModified)
    {
        this.TEC_CEDA.editComponent(pID, pComponentModified, UserType.CEDAManager);
    }

    public override Component getComponent(string pId)
    {
        return this.TEC_CEDA.getComponent(pId);
    }

    public override DocumentContext getDocument()
    {
        return this.getDocument();
    }

    public override void removeComponent(string pId)
    {
        this.TEC_CEDA.removeComponent(pId, UserType.CEDAManager);
    }
}

