//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class CEDAManager : User
{
    public TEC_CEDA TEC_CEDA;

    public CEDAManager(string pName, string pEmail, TEC_CEDA plantilla) : base(pName, pEmail)
    {
        this.TEC_CEDA = plantilla;
    }
}

