//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Component
{
    private string title;

    private string Id;

    public Component(string pTitle, string pId)
    {
        this.title = pTitle;
        this.Id = pId;
    }

	public virtual string getTitle()
	{
        return this.title;
	}

    public virtual string getId()
    {
        return this.Id;
    }

    public virtual void setTitle(string pTitle)
	{
        this.title = pTitle;
	}

}

