//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Component
{
	private string title
	{
		get;
		set;
	}

	private string Id
	{
		get;
		set;
	}

	public virtual string getTitle()
	{
		throw new System.NotImplementedException();
	}

	public virtual void setTitle(string pTitle)
	{
		throw new System.NotImplementedException();
	}

	public virtual string getId()
	{
		throw new System.NotImplementedException();
	}

}

