//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class CompositeElement : Component
{
    private Dictionary<int, bool> access;

    private List<Component> componentList;

    public CompositeElement(string pTitle, string pId, Dictionary<int, bool> pAccess) : base(pTitle, pId)
    {
        componentList = new List<Component>();
    }

    public void activateAccessLevel(int pLevel)
	{
        access[pLevel] = true;
	}

	public void deactivateAccessLevel(int pLevel)
	{
        access[pLevel] = false;
    }

    public Dictionary<int, bool> getAccessLevels()
    {
        return this.access;
    }

	protected void add(Component pComponent)
	{
        this.componentList.Add(pComponent);
	}

	public virtual void remove(string pId)
	{
        Component toRemove = this.getChild(pId);
        this.componentList.Remove(toRemove);
	}

	public Component getChild(string pId)
	{
        Component result = null;
        int maxI = this.componentList.Count;
		for (int i = 0; i < maxI; i++)
        {
            if (this.componentList[i].getId().Equals(pId))
            {
                result = this.componentList[i];
            }
        }
        return result;
	}

    public Component getChild(int pIndex)
    {
        return this.componentList.ElementAt<Component>(pIndex);
    }

    public int getChildCount()
    {
        return this.componentList.Count;
    }
}

