//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Component
{
    private string title;

    private string Id;

    private Dictionary<UserType, bool> access;

    public Component(string pTitle, string pId, Dictionary<UserType, bool> pAccess)
    {
        this.title = pTitle;
        this.Id = pId;
        this.access = pAccess;
    }

	public virtual string getTitle()
	{
        return this.title;
	}

    public virtual string getId()
    {
        return this.Id;
    }

    public virtual void setTitle(string pTitle)
	{
        this.title = pTitle;
	}

    public abstract bool isLeaf();

    public abstract Component getComponent(string pId);

    public void activateAccessLevel(UserType pLevel)
    {
        access[pLevel] = true;
    }

    public void deactivateAccessLevel(UserType pLevel)
    {
        access[pLevel] = false;
    }

    public Dictionary<UserType, bool> getAccessLevels()
    {
        return this.access;
    }

    public void setAccessLevels(Dictionary<UserType, bool> pAccessLevel)
    {
        this.access = pAccessLevel;
    }

}

