//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class CurricularManager : User
{

    public CareerPlan PlanCarrera;

    public CurricularManager(string pName, string pEmail, CareerPlan pPlan) : base(pName, pEmail)
    {
        this.PlanCarrera = pPlan;
    }
}

