//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class CurricularManager : User
{

    public CareerPlan planCarrera;

    public CurricularManager(string pName, string pEmail, CareerPlan pPlan) : base(pName, pEmail)
    {
        this.planCarrera = pPlan;
    }

    public override void addComponent(string pParentID, Component pComponent)
    {
        this.planCarrera.addComponent(pParentID, pComponent, UserType.CurricularManager);
    }

    public override void editComponent(string pID, Component pComponentModified)
    {
        this.planCarrera.editComponent(pID, pComponentModified, UserType.CurricularManager);
    }

    public override DocumentContext getDocument()
    {
        return this.planCarrera.getDocument();
    }

    public override void removeComponent(string pId)
    {
        this.planCarrera.removeComponent(pId, UserType.CurricularManager);
    }

    public override Component getComponent(string pId)
    {
        return this.planCarrera.getComponent(pId);
    }
}

