//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Curse : Observer
{
	private string Id
	{
		get;
		set;
	}

	public virtual CareerPlan CareerPlan
	{
		get;
		set;
	}

	/// <summary>
	/// Requisits
	/// </summary>
	public virtual IEnumerable<Curse> Curse
	{
		get;
		set;
	}

	/// <summary>
	/// Corequisits
	/// </summary>
	public virtual IEnumerable<Curse> Curse
	{
		get;
		set;
	}

	public virtual DocumentContext getDocument()
	{
		throw new System.NotImplementedException();
	}

	public virtual void setDocument(DocumentContext pDocument)
	{
		throw new System.NotImplementedException();
	}

}

