//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DocumentOriginator
{
    private DocumentMemento state;

	public DocumentMemento createMemento()
	{
        DocumentContext mementoState = state.getState();
        return new DocumentMemento(mementoState.clone());
	}

	public void setMemento(DocumentMemento pMemento)
	{
        this.state = pMemento;
	}

}

