//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DocumentContext : CompositeElement, Prototype
{
	public virtual DocumentState DocumentState
	{
		get;
		set;
	}

	public virtual DocumentOriginator DocumentOriginator
	{
		get;
		set;
	}

	public virtual void add(string pId, SectionContext pComponent)
	{
		throw new System.NotImplementedException();
	}

	public virtual void changeState(DocumentState pState)
	{
		throw new System.NotImplementedException();
	}

	public virtual Prototype clone()
	{
		throw new System.NotImplementedException();
	}

}

