//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DocumentMemento
{
	private DocumentContext state
	{
		get;
		set;
	}

	public virtual DocumentContext getState()
	{
		throw new System.NotImplementedException();
	}

	public virtual void setState(DocumentContext pState)
	{
		throw new System.NotImplementedException();
	}

}

