//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DocumentOriginator
{
	private DocumentMemento state
	{
		get;
		set;
	}

	public virtual DocumentMemento createMemento()
	{
		throw new System.NotImplementedException();
	}

	public virtual void setMemento(DocumentMemento pMemento)
	{
		throw new System.NotImplementedException();
	}

}

