//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FacadeProgramCurse
{
    private User user;

    private DocumentOriginator originMemento;

    private Caretaker modifHistory;

    public FacadeProgramCurse(User pUser, DocumentOriginator pOriginator, Caretaker pCaretaker)
    {
        this.user = pUser;
        this.originMemento = pOriginator;
        this.modifHistory = pCaretaker;
    }

    public void addComponent(string pParentID, Component pComponent)
    {
        this.user.addComponent(pParentID, pComponent);
    }

    public void removeComponent(string pId)
    {
        this.user.removeComponent(pId);
    }

    public void editComponentContent(string pId, string pContent)
    {
        Component toModifyCodigoCurso = this.user.getComponent(pId);
        if (toModifyCodigoCurso.isLeaf())
        {
            ((TextLineLeaf)toModifyCodigoCurso).setTextContentLine(pContent);
        }
    }

    public void editComponentTitle(string pId, string pContent)
    {
        Component toModifyCodigoCurso = this.user.getComponent(pId);
        if (!toModifyCodigoCurso.isLeaf())
        {
            toModifyCodigoCurso.setTitle(pContent);
        }
    }

    public void activateComponentAccessLevel(string pComponentId, UserType pType)
    {
        Component toModifyAccess = this.user.getComponent(pComponentId);
        toModifyAccess.activateAccessLevel(pType);
    }

    public void deactivateComponentAccessLevel(string pComponentId, UserType pType)
    {
        Component toModifyAccess = this.user.getComponent(pComponentId);
        toModifyAccess.deactivateAccessLevel(pType);
    }

    public override string ToString()
    {
        return this.user.ToString();
    }

    public void appendChange()
    {
        this.modifHistory.add(this.originMemento.createMemento());
    }

    public DocumentContext back(int i)
    {
        return this.modifHistory.getMemento(i).getState();
    }
}

