//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ProgramCurse.Models
{
    public class FacadeProgramCurse
    {
        private User user;

        public FacadeProgramCurse(User pUser)
        {
            this.user = pUser;
        }

        public void addComponent(string pParentID, Component pComponent)
        {
            user.addComponent(pParentID, pComponent);
        }

        public void removeComponent(string pId)
        {
            user.removeComponent(pId);
        }

        public void editComponentContent(string pId, string pContent)
        {
            Component toModifyCodigoCurso = user.getComponent(pId);
            if (toModifyCodigoCurso.isLeaf())
            {
                ((TextLineLeaf)toModifyCodigoCurso).setTextContentLine(pContent);
            }
        }

        public void editComponentTitle(string pId, string pContent)
        {
            Component toModifyCodigoCurso = user.getComponent(pId);
            if (!toModifyCodigoCurso.isLeaf())
            {
                toModifyCodigoCurso.setTitle(pContent);
            }
        }

        public void activateComponentAccessLevel(string pComponentId, UserType pType)
        {
            Component toModify = user.getComponent(pComponentId);
            toModify.activateAccessLevel(pType);
        }

        public void deactivateComponentAccessLevel(string pComponentId, UserType pType)
        {
            Component toModify = user.getComponent(pComponentId);
            toModify.deactivateAccessLevel(pType);
        }

        public override string ToString()
        {
            return this.user.ToString();
        }
    }

}