//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Facade
{
    private User user;

    public void addComponent(string pParentID, Component pComponent)
    {
        user.getDocument().
    }

    public void removeComponent(string pId)
    {

    }

    public void editComponent(string pID)
    {

    }
}

