//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Final : DocumentState
{
	public virtual void add(pId:sting, pComponent: Component()
	{
		throw new System.NotImplementedException();
	}

	public virtual void remove(string pId)
	{
		throw new System.NotImplementedException();
	}

}

