//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ProgramCurse.Models
{
    public class Final : DocumentState
    {
        private State myState;
        public Final()
        {
            this.myState = State.Final;
        }
        public State getMyState()
        {
            return this.myState;
        }
    }

}