//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Professor : User
{
    public List<Curse> ProgramCurses;

    public Professor(string pName, string pEmail, List<Curse> pProgramCurses) : base(pName, pEmail)
    {
        this.ProgramCurses = pProgramCurses;
    }
}

