//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ProgramCurse
{
    private Curse curse;
    private DocumentContext document;

    public ProgramCurse(DocumentContext pDocument, Curse pCurse)
    {
        this.document = pDocument;
        this.curse = pCurse;
    }

    public DocumentContext getDocument()
	{
        return this.document;
	}
    
}

