//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ProgramCurse: DocumentContainer
{
    private Curse curse;

    public ProgramCurse(DocumentContext pDocument, Curse pCurse):base(pDocument)
    {
        this.curse = pCurse;
    }

    public override void addComponent(string pParentID, Component pComponent, UserType pType)
    {
        throw new NotImplementedException();
    }

    public override void editComponent(string pID, Component pComponentModified, UserType pType)
    {
        throw new NotImplementedException();
    }

    public override Component getComponent(string pId)
    {
        throw new NotImplementedException();
    }

    public override void removeComponent(string pId, UserType pType)
    {
        throw new NotImplementedException();
    }
}

