//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

[Serializable()]
public class SectionContext : CompositeElement
{
    public SectionContext(string pTitle, string pId) : base(pTitle, pId, new Dictionary<UserType, bool>
    {
        { UserType.Professor, true },
        { UserType.CurricularManager, true },
        { UserType.CEDAManager, true }
    })
    {

    }

    public void add(SectionContext pComponent)
	{
        base.add(pComponent);
	}

    public override void remove(string pId)
    {
        base.remove(pId);
    }

    public override string ToString()
    {
        string result = this.getTitle() + ": {\n";
        int maxI = base.getChildCount();
        for (int i = 0; i < maxI; i++)
        {
            result += (i+1).ToString() + ". " + base.getComponent(i).ToString() + "\n";
        }
        return result + "}";
    }

}

