//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class SectionContext : CompositeElement
{
    public SectionContext(string pTitle, string pId) : base(pTitle, pId, new Dictionary<int, bool>
    {
        {1, false},
        {2, true},
        {3, true}
    })
    {

    }

    public void add(string pId, SectionContext pComponent)
	{
        base.add(pId, pComponent);
	}

    public void add(string pId, TextLineLeaf pComponent)
    {
        base.add(pId, pComponent);
    }

    public override void remove(string pId)
    {
        base.remove(pId);
    }

    public override string ToString()
    {
        string result = this.getTitle() + ": {\n";
        int maxI = base.getChildCount();
        for (int i = 0; i < maxI; i++)
        {
            result += (i+1).ToString() + ". " + base.getChild(i).ToString() + "\n";
        }
        return result + "}";
    }

}

