//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TEC_CEDA
{
    private DocumentContext TECTemplate;
    public TEC_CEDA(DocumentContext pDocument)
    {
        this.TECTemplate = pDocument;
    }
	public DocumentContext getDocument()
	{
        return this.TECTemplate;
	}
}

