//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ProgramCurse.Models
{
    public class TEC_CEDA : DocumentContainer
    {
        public TEC_CEDA(DocumentContext pDocument) : base(pDocument)
        {

        }
    }
}
