//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TextLineLeaf : Component
{
	private string textContentLine
	{
		get;
		set;
	}

	public virtual string getTextContentLine()
	{
		throw new System.NotImplementedException();
	}

	public virtual void setTextContentLine(string pTextContextLine)
	{
		throw new System.NotImplementedException();
	}

}

