//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TextLineLeaf : Component
{
    private string textContentLine;

    public TextLineLeaf(string pTextContextLine, string pTitle, string pId):base(pTitle, pId)
    {
        this.textContentLine = pTextContextLine;
    }

	public string getTextContentLine()
	{
        return this.textContentLine;
	}

	public virtual void setTextContentLine(string pTextContextLine)
	{
        this.textContentLine = pTextContextLine;
	}
    
    public override string ToString()
    {
        return base.getTitle() + " " + this.getTextContentLine();
    }
}

