//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class User
{

    private string name;
    private DocumentContext document;
    private string email;

    public User(string pName, string pEmail)
    {
        this.name = pName;
        this.email = pEmail;
    }

    public string getName()
    {
        return this.name;
    }

    public string getEmail()
    {
        return this.email;
    }

    public abstract void addComponent(string pParentID, Component pComponent);

    public abstract void removeComponent(string pId);

    public abstract void editComponent(string pId, Component pComponentModified);

    public abstract Component getComponent(string pId);

    public abstract DocumentContext getDocument();
}

